### ISSUE TITLE
这个可以做浏览器用，想谷歌浏览器一样访问网页

### ISSUE THREAD

**Issue by 82318179** [mengdu/vue-electron-chrome#1]
请问大师，您这个可以做浏览器用吗，像谷歌浏览器一样访问网页，最好支持window。  长的像 这种UI
https://github.com/pd4d10/chrome-ui

**Comment by mengdu** [comment]
@82318179 可以，ui是可以做到跟chrome一样的，不过直接用chrome会更好些。
实在要做的话，可以重新写下入口页面。
