### ISSUE TITLE
怎么去掉标题栏显示的版本号

### ISSUE THREAD

**Issue by mamacmm** [mengdu/vue-electron-chrome#2]
如题，不想显示那个版本号，应该怎么设置下

**Comment by mengdu** [comment]
版本号去不掉哦，要这样的话，得重新修改代码

**Comment by mamacmm** [comment]
建议加个属性，跟标题一样的，在.env.js里面设置，设置为空字符串就不显示版本号了

**Comment by gclsoft** [comment]
怎么显示在标题栏版本号, 是怎么做到的?

**Comment by mengdu** [comment]
@gclsoft ?现在不是默认显示版本号的么？

**Comment by gclsoft** [comment]
我们的项目也想显示版本号到标题里,不知道怎么弄

**Comment by mengdu** [comment]
![image](https://user-images.githubusercontent.com/11366654/47079954-4658e580-d239-11e8-9980-8e82c8982572.png)
这个标题不是有版本号了么？你说的不是很明白，麻烦详细点，哈。

**Comment by gclsoft** [comment]
是我们的react electron项目也想有这个功能, 但不知道怎么做, 想学习一下

**Comment by gclsoft** [comment]
不然每次客户反馈问题, 都要远程去看版本号

**Comment by mengdu** [comment]
学习的话，你看下[文档](https://www.baidu.com/link?url=b_u2Z31xB4zLvHqPQBUxgVk8r2g_2euJ6BXKk-LVn7lBfa_cbtd-oM5lXn92Mlyq&wd=&eqid=c1be8a710000bd79000000065bc70d57)哈，或者你看下我的代码

**Comment by gclsoft** [comment]
找了一下午, 找不到在哪里设置的. 谢谢
