### ISSUE TITLE
electron-vue在build时报错Unresolved node modules: vue

### ISSUE THREAD

**Issue by mamacmm** [mengdu/vue-electron-chrome#3]
dev运行OK，打包的时候出错

**Comment by mengdu** [comment]
你把错误信息贴下。或者你把node_modules删掉重新npm i再试试

**Comment by mamacmm** [comment]
我开始用的cnpm，后来把node_modules删掉，用yarn试了下可以了。
最开始用npm报错，下载不下来

**Comment by mengdu** [comment]
用yarn可以就行了，没必要都用一遍包管理器。
