### ISSUE TITLE
electron webview error

### ISSUE THREAD

**Issue by qianqian05723** [mengdu/vue-electron-chrome#4]
你好！就是我想在webview.vue页面将ipcRenderer注入到一个远程页面，用下面的方法，但是报require is not defined，请问这个能解决吗？
that.webview.executeJavaScript(`const {ipcRenderer} = require('electron'); `)

**Comment by mengdu** [comment]
这样试试
```
import {
  ipcRenderer
} from 'electron'
```

**Comment by qianqian05723** [comment]
![_20180829152752](https://user-images.githubusercontent.com/17306867/44772344-2cd3df80-aba0-11e8-9140-a97687c5266b.png)
在webview标签添加 nodeintegration 属性，才能访问node API，没仔细看文档，谢谢楼主指点
