### ISSUE TITLE
您好，如何改变浏览器的字体，win10显示的都是宋体。

### ISSUE THREAD

**Issue by hebijiandai** [mengdu/vue-electron-chrome#6]
您好，如何改变浏览器的字体，win10显示的都是宋体。

**Comment by mengdu** [comment]
网页的字体是由网页里css设置的，electron壳的字体，暂时不支持设置

**Comment by hebijiandai** [comment]
我试了defaultfontfamily的设置,好像没有用,我弄了下baidu.com,也是宋体.所以是不是还是要从electron本身下手找原因呢?

**Comment by hebijiandai** [comment]
![image](https://user-images.githubusercontent.com/5127081/51191785-1e544d80-1920-11e9-8c93-a70fabcc0911.png)
大侠你看,这种情况,有的是雅黑,有的是宋体啥情况

**Comment by mengdu** [comment]
@hebijiandai 可能你body没有用指定字体，有些又指定了，所以有些就用了默认字体


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
