### ISSUE TITLE
请问怎么新建多个标签页?

### ISSUE THREAD

**Issue by toohandsome** [mengdu/vue-electron-chrome#7]
请问怎么新建多个标签页?

**Comment by mengdu** [comment]
不支持这样的功能哦



------------------ 原始邮件 ------------------
发件人: "toohandsome"<notifications@github.com>; 
发送时间: 2019年5月29日(星期三) 中午12:38
收件人: "mengdu/vue-electron-chrome"<vue-electron-chrome@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [mengdu/vue-electron-chrome] 请问怎么新建多个标签页? (#7)




请问怎么新建多个标签页?
 
&mdash;
